apiVersion: v1
kind: Service
metadata:
  name: code-tv-agent
  labels:
    run: code-tv-agent
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: code-tv-agent
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: code-tv-agent
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: code-tv-agent
    spec:
      containers:
      - name: code-tv-agent
        image: gcr.io/code-tv-service/agent:b1
        ports:
        - containerPort: 8080
